version: "3"
services:
  pgsql:
    image: "postgres:9.6-alpine"
    volumes:
      - "pgsql:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "fetusjp"
      POSTGRES_USER: "fetusjp"
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_DB: "fetusjp"
      POSTGRES_INITDB_ARGS: "--data-checksums --encoding=Unicode --locale=en_US.UTF8"
      TZ: "Asia/Tokyo"
    networks:
      - "webapp"

  webapp:
    build:
      context: "./webapp"
      dockerfile: "Dockerfile"
      args:
        GITHUB_TOKEN: "%GITHUB_TOKEN%"
    volumes:
      - "app_assets:/var/www/site/web/assets"
      - "app_logs:/var/www/site/runtime/logs"
    links:
      - "pgsql"
    networks:
      - "default"

  httpd:
    build:
      context: "./docker/httpd"
      dockerfile: "Dockerfile"
    volumes:
      - "httpd_logs:/var/log/nginx/"
      - "app_assets:/var/www/site/web/assets:ro"
    environment:
      TZ: "Asia/Tokyo"
    networks:
      - "webapp"
      - "exports"
    links:
      - "pgsql"

volumes:
  pgsql:
  app_assets:
  app_logs:
  httpd_logs:

networks:
  webapp:
  exports:
    external: true
