version: "3"
services:
  pgsql:
    image: "postgres:9.6-alpine"
    volumes:
      - "fetusjp_pgsql:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "fetusjp"
      POSTGRES_USER: "fetusjp"
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_DB: "fetusjp"
      POSTGRES_INITDB_ARGS: "--data-checksums --encoding=Unicode --locale=en_US.UTF8"
      TZ: "Asia/Tokyo"
    networks:
      - "webapp"

  httpd:
    build:
      context: "docker/httpd"
      dockerfile: "Dockerfile"
    volumes:
      - "fetusjp_logs:/log"
      - "./webapp:/app"
    environment:
      TZ: "Asia/Tokyo"
    networks:
      - "webapp"
      - "exports"
    links:
      - "pgsql"
    ports:
      - "8080:80/tcp"

volumes:
  fetusjp_pgsql:
  fetusjp_logs:

networks:
  webapp:
  exports:
    external: true
