name: 'Deploy'

on:
  workflow_run:
    workflows:
      - 'CI'
    branches:
      - 'master'
    types:
      - 'completed'

jobs:
  deploy:
    name: 'Deploy'

    runs-on: 'ubuntu-20.04'

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: 'actions/checkout@v2'

      - name: 'Set up SSH key'
        env:
          PRIVATE_KEY: '${{ secrets.ACTIONS_DEPLOY_PRIVATE_KEY_ED25519 }}'
          KNOWN_HOSTS: '${{ secrets.KNOWN_HOSTS_AYANAMI }}'
        run: |
          mkdir -p ~/.ssh

          echo "$PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          echo "$KNOWN_HOSTS" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

          chmod 700 ~/.ssh

      - name: 'Set up PHP version 8.0'
        run: |
          sudo update-alternatives --set php /usr/bin/php8.0

      - name: 'Check version tag'
        id: version_check
        run: |
          echo "::set-output name=REVISION::`bin/get-version`"

      - name: 'Deploy'
        if: ${{ steps.version_check.outputs.REVISION != '' }}
        run: |
          make bin/dep
          bin/dep deploy -o git_tty=false --tag=${{ steps.version_check.outputs.REVISION }} -- production
